[detect_tempo]

# the source is either a directory or a file, 
# if it's a directory, all the files in it will be processed, 
# if it's a file, only that file will be processed
# supported audio files are wav|mp3|flac|ogg|m4a
#source = "/Volumes/CORSAIR/Media/0_Sources/Sounds_Bank/Bach/BWV 847/80bpm/Glenn Gould - Bach - Prelude in C minor, BWV 847 Sl-19.wav"
#source = "/Volumes/CORSAIR/Media/0_Sources/Sounds_Bank/Mickael Jackson/Billie Jean/Michael Jackson - Billie Jean (Official Video)_no_dr_bass_split_by_lalalai.wav"
#source = "/Volumes/CORSAIR/Media/0_Sources/Sounds_Bank/Bach/BWV 847/timestretch/94"
source = "/Volumes/CORSAIR/Media/0_Sources/Sounds_Bank/_Drums/TS_NEON/TS_NEON_118_drum_loop_grooves_nyc_big_kit_dumb_floor_tom_3_clean.wav"

[timestretch]

# the target tempo in BPM,
# must be a positive float,
target_tempo = 240.0

# the source is either a directory or a file, 
# if it's a directory, all the files in it will be processed if they are supported audio files,
# if it's a file, only that file will be processed
# supported audio files are wav|mp3|flac|ogg|m4a
#source = "/Volumes/CORSAIR/Media/0_Sources/Sounds_Bank/Bach/BWV 847/timestretch/120.0/BWV 847 Sl-03_120.02.wav"
#source = "/Volumes/CORSAIR/Media/0_Sources/Sounds_Bank/Mickael Jackson/Billie Jean/Michael Jackson - Billie Jean (Official Video)_bass_split_by_lalalai.wav"
#source = "/Volumes/CORSAIR/Media/0_Sources/Sounds_Bank/Bach/BWV 847/80bpm"
source = "/Volumes/CORSAIR/Media/0_Sources/Sounds_Bank/_Drums/TS_NEON/TS_NEON_118_drum_loop_grooves_nyc_big_kit_dumb_floor_tom_2_clean.wav"

# the output must be a directory, 
# the processed files will be saved in it 
# they will be saved in a subdirectory named after the target tempo
#output = "/Volumes/CORSAIR/Media/0_Sources/Sounds_Bank/Mickael Jackson/Billie Jean"
output = "/Volumes/CORSAIR/Media/0_Sources/Sounds_Bank/_Drums/TS_NEON"

# define the output format, either wav or mp3, default is wav
output_format = "mp3" # wav|mp3


[convert]

# the source is either a directory or a file, 
# if it's a directory, all the files in it will be processed if they are supported audio
# if it's a file, only that file will be processed
# supported audio files are wav|mp3|flac|ogg|m4a
#source = "/Volumes/CORSAIR/Media/0_Sources/Sounds_Bank/Bach/BWV 847/timestretch/120.0"
#source = "/Volumes/CORSAIR/Media/0_Sources/Sounds_Bank/Mickael Jackson/Billie Jean/Michael Jackson - Billie Jean (Official Video)_bass_split_by_lalalai.wav"
source = "/Volumes/CORSAIR/Media/0_Sources/Sounds_Bank/Metallica/One/Metallica - One (Drums Only).wav"

output = "/Volumes/CORSAIR/Media/0_Sources/Sounds_Bank/Metallica/One/"

output_format = "mp3" # wav|mp3

