[detect_tempo]

# the source is either a directory or a file, 
# if it's a directory, all the files in it will be processed, 
# if it's a file, only that file will be processed
# supported audio files are wav|mp3|flac|ogg|m4a
#source = "/Volumes/CORSAIR/Media/0_Sources/Sounds_Bank/Bach/BWV 847/80bpm/Glenn Gould - Bach - Prelude in C minor, BWV 847 Sl-19.wav"
#source = "/Volumes/CORSAIR/Media/0_Sources/Sounds_Bank/Mickael Jackson/Billie Jean/Michael Jackson - Billie Jean (Official Video)_no_dr_bass_split_by_lalalai.wav"
#source = "/Volumes/CORSAIR/Media/0_Sources/Sounds_Bank/Bach/BWV 847/timestretch/94"
source = "/Volumes/CORSAIR/Media/0_Sources/Sounds_Bank/Beethoven/Sonata C# Minor/By Birenboim/Main/"

[[timestretch]]
# slice 2
source = "/Volumes/CORSAIR/Media/0_Sources/Sounds_Bank/Beethoven/Sonata C# Minor/By Birenboim/Main/Beethoven Piano Sonata No. 14 in C-Sharp Minor Bireboim Sl-02.wav"
output = "/Volumes/CORSAIR/Media/0_Sources/Sounds_Bank/Beethoven/Sonata C# Minor/By Birenboim/Main/"
format = "mp3"
ratio = 1.05208333333333
create_target_dir = false # store the output file in the same directory as the source file
file_tag = "50.5bpm" # add a tag to the output file name, e.g. "Beethoven Piano Sonata No. 14 in C-Sharp Minor Bireboim Sl-02_50.5bpm.mp3"

[[timestretch]]
# slice 3
source = "/Volumes/CORSAIR/Media/0_Sources/Sounds_Bank/Beethoven/Sonata C# Minor/By Birenboim/Main/Beethoven Piano Sonata No. 14 in C-Sharp Minor Bireboim Sl-03.wav"
output = "/Volumes/CORSAIR/Media/0_Sources/Sounds_Bank/Beethoven/Sonata C# Minor/By Birenboim/Main/"
format = "mp3"
ratio = 1.03061224489796
create_target_dir = false # store the output file in the same directory as the source file
file_tag = "50.5bpm" # add a tag to the output file name, e.g. "Beethoven Piano Sonata No. 14 in C-Sharp Minor Bireboim Sl-03_96bpm.mp3"

[[timestretch]]
# slice 4
source = "/Volumes/CORSAIR/Media/0_Sources/Sounds_Bank/Beethoven/Sonata C# Minor/By Birenboim/Main/Beethoven Piano Sonata No. 14 in C-Sharp Minor Bireboim Sl-04.wav"
output = "/Volumes/CORSAIR/Media/0_Sources/Sounds_Bank/Beethoven/Sonata C# Minor/By Birenboim/Main/"
format = "mp3"
ratio = 1.05208333333333
create_target_dir = false
file_tag = "50.5bpm" # add a tag to the output file name, e.g. "Beethoven Piano Sonata No. 14 in C-Sharp Minor Bireboim Sl-04_94bpm.mp3"

[convert]

# the source is either a directory or a file, 
# if it's a directory, all the files in it will be processed if they are supported audio
# if it's a file, only that file will be processed
# supported audio files are wav|mp3|flac|ogg|m4a
#source = "/Volumes/CORSAIR/Media/0_Sources/Sounds_Bank/Bach/BWV 847/timestretch/120.0"
#source = "/Volumes/CORSAIR/Media/0_Sources/Sounds_Bank/Mickael Jackson/Billie Jean/Michael Jackson - Billie Jean (Official Video)_bass_split_by_lalalai.wav"
source = "/Volumes/CORSAIR/Media/0_Sources/Sounds_Bank/Metallica/One/Metallica - One (Drums Only).wav"

output = "/Volumes/CORSAIR/Media/0_Sources/Sounds_Bank/Metallica/One/"

format = "mp3" # wav|mp3

